version: '3.1'

services:

  jobby-api:
    build: 
     context: ../api.jobby.com
    volumes:
      - ../api.jobby.com:/opt/app
    restart: always
    ports:
      - 6015:6005

  jobby-pf:
    build: 
     context: ../pf.jobby
    restart: always
    ports:
      - 11010:11000

  jobby-front:
    build: 
     context: ../front
    volumes:
      - ../front:/opt/app
    restart: always
    ports:
      - 8010:8080

  jobby-admin:
    build: 
     context: ../jobby_admin_v1
    restart: always
    ports:
      - 4015:80
   

  jobbydb:
    volumes: 
      - ./jobbydb:/docker-entrypoint-initdb.d
      - jobbyvolumes:/var/lib/mysql:rw
    image: mysql:5.7
    restart: always
    ports:
     - 3307:3306
    environment:
      MYSQL_DATABASE: jobbydb
      MYSQL_USER: lidian
      MYSQL_PASSWORD: 31101978
      MYSQL_ROOT_PASSWORD: 31101978
      
volumes:
  jobbyvolumes: